### ISSUE TITLE
Add Functional Score Dialog - miscellaneous

### ISSUE THREAD

**Issue by lpeyton** [uoForms/CWS-React#23]
Use Safari as much as possible for testing
MAKE SURE when Domain Selected that you change Subdomain to "Select" and update the drop downlist.

Have Assessment Date as last field

For Capacity and Performance
-need capacity score, capacity comment, performance score, performance comment
-AND only 1 of capacity or performance score is required ... not both

**Comment by yjian118** [comment]
What is the correct order for subdomain? Make it consistent in both the filter, report and functional score drop down.

**Comment by yjian118** [comment]
The order for subdomains has been adjusted by a new plan of the subdomains id
