### ISSUE TITLE
+ (add) and x (delete) score from report

### ISSUE THREAD

**Issue by lpeyton** [uoForms/CWS-React#24]
Should have a + and x icon for each row in report.

x should prompt user to confirm .. and require a comment  (that replaces the existing comment in the item being deleted).  (for capacity and performance replace both comments with the same comment.

Row is not actually deleted .. it is either moved (deleted and inserted) to a deleted scores table or marked as deleted.

**Comment by yjian118** [comment]
Use API providered by Yuxing to delete
