### ISSUE TITLE
Report Filters

### ISSUE THREAD

**Issue by lpeyton** [uoForms/CWS-React#25]
Filter drop downs under Report Banner
Choose "all" or a specific care provider (list from database)
Choose "all" or a specific subdomain (list from database)
Choose "all" or ">3"

By default "All" is selected.

**Comment by rashinagpal** [comment]
- Score filter is added for Impatient ADLs and IADLs with name 'Score' and options : All, 3 or 4 and 4.
- All filters are working simultaneously and are reset if category or patient changes
- Score filter is not added to Rehab FIM as requested
- Care Provider is renamed to Provider
